apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true 

configMapGenerator:

- namespace: crossplane-system
  name: pythonic-composites
  options:
    labels:
      function-pythonic.package: 'kubernetescluster.KubernetesClusterComposite'
  files:
  - kubernetescluster.py

resources:
- composition.yaml
- xr.yaml
